#pragma once

typedef void(__stdcall* LPNetEventCallBack)(int event_type, const char*, void* user_data);

enum EventType {
  EVENT_WIFI_SCAN_COMPLETE = 0x0F000001,
  EVENT_WIFI_SCAN_FAIL,
  EVENT_WIFI_CONNECTION_START,
  EVENT_WIFI_CONNECTION_COMPLETE,
  EVENT_WIFI_CONNECTION_ATTEMPT_FAIL,
  EVENT_WIFI_DISCONNECTING,
  EVENT_WIFI_DISCONNECTED,

  EVENT_ETH_LIST_ACHIEVE = 0x0F100001,
  EVENT_ETH_CONNECTION_COMPLETE,
  EVENT_ETH_CONNECTION_FAIL,
  EVENT_ETH_CONNECTION_TIMEOUT,
  EVENT_ETH_LOGOFF_SUCCESS,
  EVENT_ETH_LOGOFF_TIMEOUT,
};